### ISSUE TITLE
Whitelist IP when using IpRateLimitFilter

### ISSUE THREAD

**Issue by leangl** [sief/play-guard#13]
Similarly to how we can do it with GlobalFilter, it would be useful to also be able to whitelist IP addresses when using IpRateLimitFilter.

**Comment by sief** [comment]
I've just added a parameter `ipWhitelist: Set[String] = Set.empty` to `IpRateLimitFilter.apply`. 
@lglossman Does this meet your needs?

**Comment by sief** [comment]
part of release 2.4.0
