### ISSUE TITLE
Using Play Guard in HttpErrorHandler

### ISSUE THREAD

**Issue by vuongbason994** [sief/play-guard#3]
Hi Simon, 

My apologies for posting this here; this is not an issue but more of an implementation question. I am trying to implement the "HttpErrorRateLimitAction" on my auth controller, however if there is a body parsing error, the entire action is caught by the default http error handler and rate limiting will not work in this instance.

I have been trying to implement it in my custom "HttpErrorHandler" but I'm not quite sure as to where (or rather how) I should place the code.

```
def onClientError(request: RequestHeader, statusCode: Int, message: String) = {
    
    HttpErrorRateLimitAction(new RateLimiter(2, 1f / 10, "test failure rate limit")) {
      request => BadRequest("failure rate exceeded")
    }

    Logger.error("Client Error (" + statusCode + "):" + message)
    Future.successful(
      //Status(statusCode)("A client error occurred: " + message)
      BadRequest(Json.obj("status" -> Messages("unknown.error")))
    )
  } 
```

**Comment by sief** [comment]
Can you post the signature of the action where you want to limit the http error rate?

**Comment by vuongbason994** [comment]
Hi Simon, this is the original action where I implemented the rate limiter:

```
private val httpErrorRateLimited = HttpErrorRateLimitAction(new RateLimiter(3, 1f / 30, "test failure rate limit")) { _ => BadRequest(Json.obj("status" -> Messages("rate.limited.30"))) }

    /**
     * The login function uses silhouette's unsecured action which checks if there is a non-authenticated user. 
     * If user is authenticated, it should return the CustomUnsecuredErrorHandler functions.
     *
     * @return The result to display.
     */
    def adminLogin = (httpErrorRateLimited andThen silhouette.UnsecuredAction).async(parse.json) { implicit request =>

        request.body.validate[UserLogin] match { // validate the user login object declared in user model       
          case s: JsSuccess[UserLogin] => // validation checks passed
            val userName = (request.body \ "userName").as[String]
            val password = (request.body \ "password").as[String]
            val rememberMe = (request.body \ "rememberMe").as[Boolean]

            val credentials = Credentials(userName.toLowerCase(), password)
            credentialsProvider.authenticate(credentials).flatMap { loginInfo =>
              userService.retrieve(loginInfo).flatMap { // check if username exists by querying login info
...
```
Thanks so much for your help!

**Comment by sief** [comment]
ok, the problem is, that the Action's BodyParser comes first, and if parsing fails, the limiter is not even reached. If you really want to limit the parsing error rate, too, you could do the parsing in your Action's code. E.g.:

```
  def test = httpErrorRateLimited(parse.raw) { request =>
    val jsO = request.body.asBytes().flatMap(b => Try(Json.parse(b.iterator.asInputStream)).toOption)
    jsO.fold(BadRequest("invalid json")) { js =>
      // ....
      Ok("test")
    }
  }
```

Just an example, but the the parsing errors get caught by the limiter.

**Comment by vuongbason994** [comment]
Thanks Simon! May I know if there is a way to implement the limiter globally such that all requests and errors can be "caught" prior to code execution? (e.g. in the error handler)

I am building a rest api and although the application is yet to be in production, I am seeing many strange requests and attempts (probably by bots) randomly hitting un-named routes.

**Comment by sief** [comment]
these limit actions like HttpErrorRateLimitAction  are actually meant to be used for application specific errors. If you want to do global rate limiting, take a look at https://github.com/sief/play-guard#1-guardfilter.
This global filter currently doesn't limit error rates, but take a look at the source code, it shouldn't be too difficult to implement this. I'll add this feature to my backlog ;)
