### ISSUE TITLE
Max global rate limit

### ISSUE THREAD

**Issue by salman-ie** [sief/play-guard#6]
I was going through the code and it seems like at line https://github.com/sief/play-guard/blob/master/module/app/com/digitaltangible/tokenbucket/TokenBucketGroup.scala#L104 , the rate limit can not exceed 1000 req/sec. How can I have the global rate limit set to something like 2000 req/sec?

Thanks in advance!!

**Comment by sief** [comment]
right, the two upper limits are not necessary, I think we can remove lines 104 and 106. 
Would you like to submit a pull request?

**Comment by salman-ie** [comment]
Sure will do. Thanks for the clarification

**Comment by sief** [comment]
please keep in mind that the token bucket access is sequential. Depending on your hardware resources there will be a request rate limit the limiter can handle. (resulting in a growing actor mailbox and ask timeouts).

**Comment by sief** [comment]
the reason for the limit was the resolution of milliseconds. I've just changed that to nanoseconds. The new limit is 1000000000
